### ISSUE TITLE
[Bug]: Condition on Objectbrick not working

### ISSUE THREAD

**Issue by LukasLoeffler** [pimcore/advanced-object-search#151]
### Expected behavior

Usually conditions can be added via **+ > Condition > Field > Operator > Value**

### Actual behavior

To search ObjectBricks you have to click **+ > Condition > Type > Field > Operator > Value**
The error occurs after selecting the type of the ObjectBrick to search for.
![image](https://user-images.githubusercontent.com/24526399/165768222-2878f01f-f8e2-456b-8b34-401f00dd73d9.png)
After clicking on one of the types the following error message occurs:
![image](https://user-images.githubusercontent.com/24526399/165768447-e98c473a-a946-40fd-8a27-a4b424cc0d93.png)

Clicking on details reveal the following error message:
```
Timestamp: Thu Apr 28 2022 15:57:07 GMT+0200 (Mitteleuropäische Sommerzeit)
Status: 500 | Internal Server Error
URL: /admin/bundle/advanced-object-search/admin/get-fields?_dc=1651154227245
Method: GET
Message: Call to undefined method getName in class Pimcore\Model\DataObject\Objectbrick\Definition
Trace: 
in /var/www/html/vendor/pimcore/pimcore/lib/Model/AbstractModel.php:257
#0 /var/www/html/vendor/pimcore/advanced-object-search/src/Service.php(159): Pimcore\Model\AbstractModel->__call('getName', Array)
#1 /var/www/html/vendor/pimcore/advanced-object-search/src/Controller/AdminController.php(75): AdvancedObjectSearchBundle\Service->getFieldSelectionInformationForClassDefinition(Object(Pimcore\Model\DataObject\Objectbrick\Definition), true)
#2 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(152): AdvancedObjectSearchBundle\Controller\AdminController->getFieldsAction(Object(Symfony\Component\HttpFoundation\Request), Object(AdvancedObjectSearchBundle\Service))
#3 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(74): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1)
#4 /var/www/html/vendor/symfony/http-kernel/Kernel.php(202): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#5 /var/www/html/public/index.php(36): Symfony\Component\HttpKernel\Kernel->handle(Object(Symfony\Component\HttpFoundation\Request))
#6 {main}
```

### Steps to reproduce

The error can be reproduced on the EnterpriseDemo at [demo.pimcore.com](https://demo.pimcore.com/admin/) by the following steps:

1. Open new AdvancedObjectSearch
2. Create filter for class "Car"
3. Add condition
4. Select Field Attributes
5. Select one of the types

**Comment by LukasLoeffler** [comment]
I have testes the supplied fix by @kingjia90.
Now the search is working as expected.
Thanks!
